query PoolIDs($blockNumber: Int!, $bal: Bytes!) {
  pools(
    where: { tokensList_contains: [$bal] }
    block: { number: $blockNumber }
  ) {
    id
  }
}

query Pool(
  $blockNumber: Int!
  $bal: Bytes!
  $poolId: ID!
  $sharesSkip: Int!
  $sharesLimit: Int!
) {
  pools(
    where: { id: $poolId, tokensList_contains: [$bal] }
    block: { number: $blockNumber }
  ) {
    id
    shares(
      first: $sharesLimit
      skip: $sharesSkip
      orderDirection: desc
      orderBy: balance
    ) {
      userAddress {
        id
      }
      balance
    }
    tokens {
      address
      weight
      balance
    }
  }
}
