query VotingEscrowLocks($blockNumber: Int!) {
  votingEscrowLocks(
    first: 1000
    orderBy: lockedBalance
    orderDirection: desc
    block: { number: $blockNumber }
  ) {
    id
    lockedBalance
  }
}
